#!/bin/bash
apt-get update && apt-get -y install git python3 hostname apache2
git clone https://github.com/ProfessionalLinuxUsersGroup/course-books && cd course-books
python3 -m venv . && source "$PWD"/bin/activate
pip install -U pip && pip install -U mkdocs mkdocs-material mkdocs-glightbox
# use mkdocs serve -a "$(hostname -I | awk '{print $1}'):8000" for live reloading
mkdocs build -d /var/www/html/ && systemctl enable --now apache2
