#!/bin/bash
apt-get update && apt-get -y install git python3.13-full hostname apache2 weasyprint
git clone https://github.com/ProfessionalLinuxUsersGroup/course-books
cd course-books
python3.13 -m venv "$PWD"
source venv/bin/activate
pip install -U pip
pip install -U mkdocs mkdocs-material mkdocs-glightbox mkdocs-to-pdf
# use mkdocs serve -a "$(hostname -I | awk '{print $1}'):8000" for live reloading after changes
mkdocs build -d /var/www/html/ && systemctl enable --now apache2
